In [13]:
import pandas as pd

In [14]:
t=pd.read_csv('titanic.csv')

In [15]:
age=t.loc[::,'age']
type(age)#Age here is a series

pandas.core.series.Series

In [16]:
#Certain methods and attributes work for both Dataframes and Series
#some methods only work for either one of them

In [17]:
age.head()

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
Name: age, dtype: float64

In [18]:
age.tail()

886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: age, dtype: float64

In [19]:
age.info#doest work for Series

AttributeError: 'Series' object has no attribute 'info'

In [20]:
age.shape

(891,)

In [21]:
age.index

RangeIndex(start=0, stop=891, step=1)

In [22]:
age.describe()

count    714.000000
mean      29.699118
std       14.526497
min        0.420000
25%       20.125000
50%       28.000000
75%       38.000000
max       80.000000
Name: age, dtype: float64

In [23]:
age.dtype

dtype('float64')

In [24]:
print(age.count())
len(age)

714

891

In [25]:
print(age.sum())#exclude nan values
print(sum(age))#conside nan values

21205.17
nan

In [26]:
age.mean(skipna=False)

nan

In [27]:
age.median()

28.0

In [28]:
age.std()

14.526497332334044

In [29]:
age.ptp()#(max-min)

79.579999999999998

In [30]:
age.unique()#only available for Series

array([ 22.  ,  38.  ,  26.  ,  35.  ,    nan,  54.  ,   2.  ,  27.  ,
        14.  ,   4.  ,  58.  ,  20.  ,  39.  ,  55.  ,  31.  ,  34.  ,
        15.  ,  28.  ,   8.  ,  19.  ,  40.  ,  66.  ,  42.  ,  21.  ,
        18.  ,   3.  ,   7.  ,  49.  ,  29.  ,  65.  ,  28.5 ,   5.  ,
        11.  ,  45.  ,  17.  ,  32.  ,  16.  ,  25.  ,   0.83,  30.  ,
        33.  ,  23.  ,  24.  ,  46.  ,  59.  ,  71.  ,  37.  ,  47.  ,
        14.5 ,  70.5 ,  32.5 ,  12.  ,   9.  ,  36.5 ,  51.  ,  55.5 ,
        40.5 ,  44.  ,   1.  ,  61.  ,  56.  ,  50.  ,  36.  ,  45.5 ,
        20.5 ,  62.  ,  41.  ,  52.  ,  63.  ,  23.5 ,   0.92,  43.  ,
        60.  ,  10.  ,  64.  ,  13.  ,  48.  ,   0.75,  53.  ,  57.  ,
        80.  ,  70.  ,  24.5 ,   6.  ,   0.67,  30.5 ,   0.42,  34.5 ,  74.  ])

In [31]:
age.nunique()#Count unique values

88

In [32]:
age.value_counts()

24.00    30
22.00    27
18.00    26
19.00    25
30.00    25
28.00    25
21.00    24
25.00    23
36.00    22
29.00    20
32.00    18
27.00    18
35.00    18
26.00    18
16.00    17
31.00    17
20.00    15
33.00    15
23.00    15
34.00    15
39.00    14
17.00    13
42.00    13
40.00    13
45.00    12
38.00    11
50.00    10
2.00     10
4.00     10
47.00     9
         ..
71.00     2
59.00     2
63.00     2
0.83      2
30.50     2
70.00     2
57.00     2
0.75      2
13.00     2
10.00     2
64.00     2
40.50     2
32.50     2
45.50     2
20.50     1
24.50     1
0.67      1
14.50     1
0.92      1
74.00     1
34.50     1
80.00     1
12.00     1
36.50     1
53.00     1
55.50     1
70.50     1
66.00     1
23.50     1
0.42      1
Name: age, Length: 88, dtype: int64

In [33]:
age.value_counts(normalize=False,sort=True,ascending=False,dropna=False)

NaN       177
 24.00     30
 22.00     27
 18.00     26
 28.00     25
 19.00     25
 30.00     25
 21.00     24
 25.00     23
 36.00     22
 29.00     20
 32.00     18
 26.00     18
 35.00     18
 27.00     18
 16.00     17
 31.00     17
 34.00     15
 23.00     15
 33.00     15
 20.00     15
 39.00     14
 17.00     13
 42.00     13
 40.00     13
 45.00     12
 38.00     11
 50.00     10
 2.00      10
 4.00      10
         ...
 28.50      2
 63.00      2
 0.83       2
 30.50      2
 70.00      2
 57.00      2
 0.75       2
 13.00      2
 59.00      2
 10.00      2
 64.00      2
 40.50      2
 45.50      2
 32.50      2
 20.50      1
 24.50      1
 0.67       1
 70.50      1
 0.92       1
 74.00      1
 34.50      1
 14.50      1
 80.00      1
 12.00      1
 53.00      1
 36.50      1
 55.50      1
 66.00      1
 23.50      1
 0.42       1
Name: age, Length: 89, dtype: int64

In [34]:
s=pd.read_csv('summer.csv',usecols=["Athlete"],squeeze=True)#directly obtaining a series
s

0                            HAJOS, Alfred
1                         HERSCHMANN, Otto
2                        DRIVAS, Dimitrios
3                       MALOKINIS, Ioannis
4                       CHASAPIS, Spiridon
5                    CHOROPHAS, Efstathios
6                            HAJOS, Alfred
7                         ANDREOU, Joannis
8                    CHOROPHAS, Efstathios
9                            NEUMANN, Paul
10                       PEPANOS, Antonios
11                           LANE, Francis
12                        SZOKOLYI, Alajos
13                           BURKE, Thomas
14                          HOFMANN, Fritz
15                          CURTIS, Thomas
16                      GOULDING, Grantley
17                       LERMUSIAUX, Albin
18                            FLACK, Edwin
19                           BLAKE, Arthur
20                         GMELIN, Charles
21                           BURKE, Thomas
22                        JAMISON, Herbert
23                      GOLEMIS, Dimitrios
24                            FLACK, Edwin
25                            DANI, Nandor
26                        VERSIS, Sotirios
27                         GARRETT, Robert
28             PARASKEVOPOULOS, Panagiotis
29                           CLARK, Ellery
                       ...
31135                     GAZYUMOV, Khetag
31136                  GOGSHELIDZE, George
31137                  LOPEZ NUNEZ, Mijain
31138                          NABI, Heiki
31139                         EUREN, Johan
31140                        KAYAALP, Riza
31141    SORYAN REIHANPOUR, Hamid Mohammad
31142                    BAYRAMOV, Rovshan
31143                         MODOS, Peter
31144                    SEMENOV, Mingiyan
31145                   NOROOZI, Omid Haji
31146                       LASHKHI, Revaz
31147                  KURAMAGOMEDOV, Zaur
31148                   MATSUMOTO, Ryutaro
31149                        KIM, Hyeonwoo
31150                       LORINCZ, Tamas
31151                       GUENOT, Steeve
31152                  TSKHADAIA, Manuchar
31153                        VLASOV, Roman
31154                   JULFALAKYAN, Arsen
31155                        AHMADOV, Emin
31156                 KAZAKEVIC, Aleksandr
31157                        KHUGAEV, Alan
31158         EBRAHIM, Karam Mohamed Gaber
31159                      GAJIYEV, Danyal
31160                   JANIKOWSKI, Damian
31161            REZAEI, Ghasem Gholamreza
31162                       TOTROV, Rustam
31163                    ALEKSANYAN, Artur
31164                       LIDBERG, Jimmy
Name: Athlete, Length: 31165, dtype: object

In [35]:
pd.Series([10,25,36])#Creating a series directly

0    10
1    25
2    36
dtype: int64

In [36]:
pd.Series([10,40,40],index=['mon','tue','wed'],name='money saved ')

mon    10
tue    40
wed    40
Name: money saved , dtype: int64

In [37]:
a=[1,2,3,4]#converting a list to Series(we can also turn a tuple into series)
pd.Series(a)

0    1
1    2
2    3
3    4
dtype: int64

In [38]:
d={'onion':85,'potato':35,'beans':52}#Passing dict to series
ds=pd.Series(d)
ds

beans     52
onion     85
potato    35
dtype: int64

In [39]:
da={0:2,1:4,2:5}

In [40]:
q=pd.Series(da)
q

0    2
1    4
2    5
dtype: int64

In [41]:
q.sort_index(ascending=False,inplace=True)#saves values or changes to q(initial series)

In [42]:
q

2    5
1    4
0    2
dtype: int64

In [43]:
q.sort_values(ascending=False)

2    5
1    4
0    2
dtype: int64

In [44]:
age.sort_values(ascending=False).iloc[:3,]#finding the smallest values

630    80.0
851    74.0
96     71.0
Name: age, dtype: float64

In [45]:
age.nlargest(3)#largest values, this equal the above opt with sort values and iloc

630    80.0
851    74.0
96     71.0
Name: age, dtype: float64

In [46]:
age.nsmallest(3)

803    0.42
755    0.67
469    0.75
Name: age, dtype: float64

In [47]:
age.sort_values().iloc[:1:].index[0]#Finding the index of the smallest values

803

In [48]:
age.idxmin()#Does the same as above

803

In [49]:
age.idxmax()#Finds index of largest value

630

In [50]:
sales = pd.Series([10,25,6,36,2,0,None,5], index = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun", "Mon"])
sales

Mon    10.0
Tue    25.0
Wed     6.0
Thu    36.0
Fri     2.0
Sat     0.0
Sun     NaN
Mon     5.0
dtype: float64

In [51]:
sales.loc['Sun']=0#changing value to any component of a series

In [52]:
sales

Mon    10.0
Tue    25.0
Wed     6.0
Thu    36.0
Fri     2.0
Sat     0.0
Sun     0.0
Mon     5.0
dtype: float64

In [53]:
(sales/1.42).round(2)#performing opts on each values of sales Series

Mon     7.04
Tue    17.61
Wed     4.23
Thu    25.35
Fri     1.41
Sat     0.00
Sun     0.00
Mon     3.52
dtype: float64

In [54]:
age.iloc[2]=1#changing values of indx 2 of age series of titanic

C:\Users\Haider\Desktop\New folder\lib\site-packages\pandas\core\indexing.py:189: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)

In [55]:
t.head(3)#But Value changes in data frame also

   survived  pclass     sex   age  sibsp  parch     fare embarked deck
0         0       3    male  22.0      1      0   7.2500        S  NaN
1         1       1  female  38.0      1      0  71.2833        C    C
2         1       3  female   1.0      0      0   7.9250        S  NaN

In [56]:
olym=pd.read_csv('summer.csv',index_col='Athlete')

In [57]:
olym

,Year,City,Sport,Discipline,Country,Gender,Event,Medal
Athlete,,,,,,,,
"HAJOS, Alfred",1896,Athens,Aquatics,Swimming,HUN,Men,100M Freestyle,Gold
"HERSCHMANN, Otto",1896,Athens,Aquatics,Swimming,AUT,Men,100M Freestyle,Silver
"DRIVAS, Dimitrios",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Bronze
"MALOKINIS, Ioannis",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Gold
"CHASAPIS, Spiridon",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Silver
"CHOROPHAS, Efstathios",1896,Athens,Aquatics,Swimming,GRE,Men,1200M Freestyle,Bronze
"HAJOS, Alfred",1896,Athens,Aquatics,Swimming,HUN,Men,1200M Freestyle,Gold
"ANDREOU, Joannis",1896,Athens,Aquatics,Swimming,GRE,Men,1200M Freestyle,Silver
"CHOROPHAS, Efstathios",1896,Athens,Aquatics,Swimming,GRE,Men,400M Freestyle,Bronze
"NEUMANN, Paul",1896,Athens,Aquatics,Swimming,AUT,Men,400M Freestyle,Gold
"PEPANOS, Antonios",1896,Athens,Aquatics,Swimming,GRE,Men,400M Freestyle,Silver
"LANE, Francis",1896,Athens,Athletics,Athletics,USA,Men,100M,Bronze
"SZOKOLYI, Alajos",1896,Athens,Athletics,Athletics,HUN,Men,100M,Bronze
"BURKE, Thomas",1896,Athens,Athletics,Athletics,USA,Men,100M,Gold
"HOFMANN, Fritz",1896,Athens,Athletics,Athletics,GER,Men,100M,Silver
"CURTIS, Thomas",1896,Athens,Athletics,Athletics,USA,Men,110M Hurdles,Gold
"GOULDING, Grantley",1896,Athens,Athletics,Athletics,GBR,Men,110M Hurdles,Silver
"LERMUSIAUX, Albin",1896,Athens,Athletics,Athletics,FRA,Men,1500M,Bronze
"FLACK, Edwin",1896,Athens,Athletics,Athletics,AUS,Men,1500M,Gold
"BLAKE, Arthur",1896,Athens,Athletics,Athletics,USA,Men,1500M,Silver
"GMELIN, Charles",1896,Athens,Athletics,Athletics,GBR,Men,400M,Bronze
"BURKE, Thomas",1896,Athens,Athletics,Athletics,USA,Men,400M,Gold
"JAMISON, Herbert",1896,Athens,Athletics,Athletics,USA,Men,400M,Silver
"GOLEMIS, Dimitrios",1896,Athens,Athletics,Athletics,GRE,Men,800M,Bronze
"FLACK, Edwin",1896,Athens,Athletics,Athletics,AUS,Men,800M,Gold
"DANI, Nandor",1896,Athens,Athletics,Athletics,HUN,Men,800M,Silver
"VERSIS, Sotirios",1896,Athens,Athletics,Athletics,GRE,Men,Discus Throw,Bronze
"GARRETT, Robert",1896,Athens,Athletics,Athletics,USA,Men,Discus Throw,Gold
"PARASKEVOPOULOS, Panagiotis",1896,Athens,Athletics,Athletics,GRE,Men,Discus Throw,Silver
"CLARK, Ellery",1896,Athens,Athletics,Athletics,USA,Men,High Jump,Gold
...,...,...,...,...,...,...,...,...
"GAZYUMOV, Khetag",2012,London,Wrestling,Wrestling Freestyle,AZE,Men,Wf 96 KG,Bronze
"GOGSHELIDZE, George",2012,London,Wrestling,Wrestling Freestyle,GEO,Men,Wf 96 KG,Bronze
"LOPEZ NUNEZ, Mijain",2012,London,Wrestling,Wrestling Freestyle,CUB,Men,Wg 120 KG,Gold
"NABI, Heiki",2012,London,Wrestling,Wrestling Freestyle,EST,Men,Wg 120 KG,Silver
"EUREN, Johan",2012,London,Wrestling,Wrestling Freestyle,SWE,Men,Wg 120 KG,Bronze
"KAYAALP, Riza",2012,London,Wrestling,Wrestling Freestyle,TUR,Men,Wg 120 KG,Bronze
"SORYAN REIHANPOUR, Hamid Mohammad",2012,London,Wrestling,Wrestling Freestyle,IRI,Men,Wg 55 KG,Gold
"BAYRAMOV, Rovshan",2012,London,Wrestling,Wrestling Freestyle,AZE,Men,Wg 55 KG,Silver
"MODOS, Peter",2012,London,Wrestling,Wrestling Freestyle,HUN,Men,Wg 55 KG,Bronze
"SEMENOV, Mingiyan",2012,London,Wrestling,Wrestling Freestyle,RUS,Men,Wg 55 KG,Bronze
"NOROOZI, Omid Haji",2012,London,Wrestling,Wrestling Freestyle,IRI,Men,Wg 60 KG,Gold
"LASHKHI, Revaz",2012,London,Wrestling,Wrestling Freestyle,GEO,Men,Wg 60 KG,Silver
"KURAMAGOMEDOV, Zaur",2012,London,Wrestling,Wrestling Freestyle,RUS,Men,Wg 60 KG,Bronze
"MATSUMOTO, Ryutaro",2012,London,Wrestling,Wrestling Freestyle,JPN,Men,Wg 60 KG,Bronze
"KIM, Hyeonwoo",2012,London,Wrestling,Wrestling Freestyle,KOR,Men,Wg 66 KG,Gold
"LORINCZ, Tamas",2012,London,Wrestling,Wrestling Freestyle,HUN,Men,Wg 66 KG,Silver
"GUENOT, Steeve",2012,London,Wrestling,Wrestling Freestyle,FRA,Men,Wg 66 KG,Bronze
"TSKHADAIA, Manuchar",2012,London,Wrestling,Wrestling Freestyle,GEO,Men,Wg 66 KG,Bronze
"VLASOV, Roman",2012,London,Wrestling,Wrestling Freestyle,RUS,Men,Wg 74 KG,Gold
"JULFALAKYAN, Arsen",2012,London,Wrestling,Wrestling Freestyle,ARM,Men,Wg 74 KG,Silver
"AHMADOV, Emin",2012,London,Wrestling,Wrestling Freestyle,AZE,Men,Wg 74 KG,Bronze
"KAZAKEVIC, Aleksandr",2012,London,Wrestling,Wrestling Freestyle,LTU,Men,Wg 74 KG,Bronze
"KHUGAEV, Alan",2012,London,Wrestling,Wrestling Freestyle,RUS,Men,Wg 84 KG,Gold
"EBRAHIM, Karam Mohamed Gaber",2012,London,Wrestling,Wrestling Freestyle,EGY,Men,Wg 84 KG,Silver
"GAJIYEV, Danyal",2012,London,Wrestling,Wrestling Freestyle,KAZ,Men,Wg 84 KG,Bronze
"JANIKOWSKI, Damian",2012,London,Wrestling,Wrestling Freestyle,POL,Men,Wg 84 KG,Bronze
"REZAEI, Ghasem Gholamreza",2012,London,Wrestling,Wrestling Freestyle,IRI,Men,Wg 96 KG,Gold
"TOTROV, Rustam",2012,London,Wrestling,Wrestling Freestyle,RUS,Men,Wg 96 KG,Silver
"ALEKSANYAN, Artur",2012,London,Wrestling,Wrestling Freestyle,ARM,Men,Wg 96 KG,Bronze
"LIDBERG, Jimmy",2012,London,Wrestling,Wrestling Freestyle,SWE,Men,Wg 96 KG,Bronze

In [58]:
olym.columns[:3]

Index(['Year', 'City', 'Sport'], dtype='object')

In [59]:
olym.index[:10].unique()

Index(['HAJOS, Alfred', 'HERSCHMANN, Otto', 'DRIVAS, Dimitrios',
       'MALOKINIS, Ioannis', 'CHASAPIS, Spiridon', 'CHOROPHAS, Efstathios',
       'ANDREOU, Joannis', 'NEUMANN, Paul'],
      dtype='object', name='Athlete')

In [60]:
olym.index[4]

'CHASAPIS, Spiridon'

In [61]:
olym.index.get_loc('CHASAPIS, Spiridon')#getting loc of data or particular index

4

In [62]:
olym.index.is_unique

False

In [63]:
a=pd.Index(['m','t','w'])#Creating an index

#Curve brackets for creating and square brackets for already existing Series/DF

In [64]:
pd.Series([10,40,70],index=a,name='Sales')

m    10
t    40
w    70
Name: Sales, dtype: int64

In [65]:
olym.head()

,Year,City,Sport,Discipline,Country,Gender,Event,Medal
Athlete,,,,,,,,
"HAJOS, Alfred",1896,Athens,Aquatics,Swimming,HUN,Men,100M Freestyle,Gold
"HERSCHMANN, Otto",1896,Athens,Aquatics,Swimming,AUT,Men,100M Freestyle,Silver
"DRIVAS, Dimitrios",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Bronze
"MALOKINIS, Ioannis",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Gold
"CHASAPIS, Spiridon",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Silver

In [66]:
olym.reset_index()

,Athlete,Year,City,Sport,Discipline,Country,Gender,Event,Medal
0,"HAJOS, Alfred",1896,Athens,Aquatics,Swimming,HUN,Men,100M Freestyle,Gold
1,"HERSCHMANN, Otto",1896,Athens,Aquatics,Swimming,AUT,Men,100M Freestyle,Silver
2,"DRIVAS, Dimitrios",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Bronze
3,"MALOKINIS, Ioannis",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Gold
4,"CHASAPIS, Spiridon",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Silver
5,"CHOROPHAS, Efstathios",1896,Athens,Aquatics,Swimming,GRE,Men,1200M Freestyle,Bronze
6,"HAJOS, Alfred",1896,Athens,Aquatics,Swimming,HUN,Men,1200M Freestyle,Gold
7,"ANDREOU, Joannis",1896,Athens,Aquatics,Swimming,GRE,Men,1200M Freestyle,Silver
8,"CHOROPHAS, Efstathios",1896,Athens,Aquatics,Swimming,GRE,Men,400M Freestyle,Bronze
9,"NEUMANN, Paul",1896,Athens,Aquatics,Swimming,AUT,Men,400M Freestyle,Gold
10,"PEPANOS, Antonios",1896,Athens,Aquatics,Swimming,GRE,Men,400M Freestyle,Silver
11,"LANE, Francis",1896,Athens,Athletics,Athletics,USA,Men,100M,Bronze
12,"SZOKOLYI, Alajos",1896,Athens,Athletics,Athletics,HUN,Men,100M,Bronze
13,"BURKE, Thomas",1896,Athens,Athletics,Athletics,USA,Men,100M,Gold
14,"HOFMANN, Fritz",1896,Athens,Athletics,Athletics,GER,Men,100M,Silver
15,"CURTIS, Thomas",1896,Athens,Athletics,Athletics,USA,Men,110M Hurdles,Gold
16,"GOULDING, Grantley",1896,Athens,Athletics,Athletics,GBR,Men,110M Hurdles,Silver
17,"LERMUSIAUX, Albin",1896,Athens,Athletics,Athletics,FRA,Men,1500M,Bronze
18,"FLACK, Edwin",1896,Athens,Athletics,Athletics,AUS,Men,1500M,Gold
19,"BLAKE, Arthur",1896,Athens,Athletics,Athletics,USA,Men,1500M,Silver
20,"GMELIN, Charles",1896,Athens,Athletics,Athletics,GBR,Men,400M,Bronze
21,"BURKE, Thomas",1896,Athens,Athletics,Athletics,USA,Men,400M,Gold
22,"JAMISON, Herbert",1896,Athens,Athletics,Athletics,USA,Men,400M,Silver
23,"GOLEMIS, Dimitrios",1896,Athens,Athletics,Athletics,GRE,Men,800M,Bronze
24,"FLACK, Edwin",1896,Athens,Athletics,Athletics,AUS,Men,800M,Gold
25,"DANI, Nandor",1896,Athens,Athletics,Athletics,HUN,Men,800M,Silver
26,"VERSIS, Sotirios",1896,Athens,Athletics,Athletics,GRE,Men,Discus Throw,Bronze
27,"GARRETT, Robert",1896,Athens,Athletics,Athletics,USA,Men,Discus Throw,Gold
28,"PARASKEVOPOULOS, Panagiotis",1896,Athens,Athletics,Athletics,GRE,Men,Discus Throw,Silver
29,"CLARK, Ellery",1896,Athens,Athletics,Athletics,USA,Men,High Jump,Gold
...,...,...,...,...,...,...,...,...,...
31135,"GAZYUMOV, Khetag",2012,London,Wrestling,Wrestling Freestyle,AZE,Men,Wf 96 KG,Bronze
31136,"GOGSHELIDZE, George",2012,London,Wrestling,Wrestling Freestyle,GEO,Men,Wf 96 KG,Bronze
31137,"LOPEZ NUNEZ, Mijain",2012,London,Wrestling,Wrestling Freestyle,CUB,Men,Wg 120 KG,Gold
31138,"NABI, Heiki",2012,London,Wrestling,Wrestling Freestyle,EST,Men,Wg 120 KG,Silver
31139,"EUREN, Johan",2012,London,Wrestling,Wrestling Freestyle,SWE,Men,Wg 120 KG,Bronze
31140,"KAYAALP, Riza",2012,London,Wrestling,Wrestling Freestyle,TUR,Men,Wg 120 KG,Bronze
31141,"SORYAN REIHANPOUR, Hamid Mohammad",2012,London,Wrestling,Wrestling Freestyle,IRI,Men,Wg 55 KG,Gold
31142,"BAYRAMOV, Rovshan",2012,London,Wrestling,Wrestling Freestyle,AZE,Men,Wg 55 KG,Silver
31143,"MODOS, Peter",2012,London,Wrestling,Wrestling Freestyle,HUN,Men,Wg 55 KG,Bronze
31144,"SEMENOV, Mingiyan",2012,London,Wrestling,Wrestling Freestyle,RUS,Men,Wg 55 KG,Bronze
31145,"NOROOZI, Omid Haji",2012,London,Wrestling,Wrestling Freestyle,IRI,Men,Wg 60 KG,Gold
31146,"LASHKHI, Revaz",2012,London,Wrestling,Wrestling Freestyle,GEO,Men,Wg 60 KG,Silver
31147,"KURAMAGOMEDOV, Zaur",2012,London,Wrestling,Wrestling Freestyle,RUS,Men,Wg 60 KG,Bronze
31148,"MATSUMOTO, Ryutaro",2012,London,Wrestling,Wrestling Freestyle,JPN,Men,Wg 60 KG,Bronze
31149,"KIM, Hyeonwoo",2012,London,Wrestling,Wrestling Freestyle,KOR,Men,Wg 66 KG,Gold
31150,"LORINCZ, Tamas",2012,London,Wrestling,Wrestling Freestyle,HUN,Men,Wg 66 KG,Silver
31151,"GUENOT, Steeve",2012,London,Wrestling,Wrestling Freestyle,FRA,Men,Wg 66 KG,Bronze
31152,"TSKHADAIA, Manuchar",2012,London,Wrestling,Wrestling Freestyle,GEO,Men,Wg 66 KG,Bronze
31153,"VLASOV, Roman",2012,London,Wrestling,Wrestling Freestyle,RUS,Men,Wg 74 KG,Gold
31154,"JULFALAKYAN, Arsen",2012,London,Wrestling,Wrestling Freestyle,ARM,Men,Wg 74 KG,Silver
31155,"AHMADOV, Emin",2012,London,Wrestling,Wrestling Freestyle,AZE,Men,Wg 74 KG,Bronze
31156,"KAZAKEVIC, Aleksandr",2012,London,Wrestling,Wrestling Freestyle,LTU,Men,Wg 74 KG,Bronze
31157,"KHUGAEV, Alan",2012,London,Wrestling,Wrestling Freestyle,RUS,Men,Wg 84 KG,Gold
31158,"EBRAHIM, Karam Mohamed Gaber",2012,London,Wrestling,Wrestling Freestyle,EGY,Men,Wg 84 KG,Silver
31159,"GAJIYEV, Danyal",2012,London,Wrestling,Wrestling Freestyle,KAZ,Men,Wg 84 KG,Bronze
31160,"JANIKOWSKI, Damian",2012,London,Wrestling,Wrestling Freestyle,POL,Men,Wg 84 KG,Bronze
31161,"REZAEI, Ghasem Gholamreza",2012,London,Wrestling,Wrestling Freestyle,IRI,Men,Wg 96 KG,Gold
31162,"TOTROV, Rustam",2012,London,Wrestling,Wrestling Freestyle,RUS,Men,Wg 96 KG,Silver
31163,"ALEKSANYAN, Artur",2012,London,Wrestling,Wrestling Freestyle,ARM,Men,Wg 96 KG,Bronze
31164,"LIDBERG, Jimmy",2012,London,Wrestling,Wrestling Freestyle,SWE,Men,Wg 96 KG,Bronze

olym.reset_index(drop=True)#will delete exixting index after reset

In [67]:
olym.set_index('Year')#set new index

,City,Sport,Discipline,Country,Gender,Event,Medal
Year,,,,,,,
1896,Athens,Aquatics,Swimming,HUN,Men,100M Freestyle,Gold
1896,Athens,Aquatics,Swimming,AUT,Men,100M Freestyle,Silver
1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Bronze
1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Gold
1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Silver
1896,Athens,Aquatics,Swimming,GRE,Men,1200M Freestyle,Bronze
1896,Athens,Aquatics,Swimming,HUN,Men,1200M Freestyle,Gold
1896,Athens,Aquatics,Swimming,GRE,Men,1200M Freestyle,Silver
1896,Athens,Aquatics,Swimming,GRE,Men,400M Freestyle,Bronze
1896,Athens,Aquatics,Swimming,AUT,Men,400M Freestyle,Gold
1896,Athens,Aquatics,Swimming,GRE,Men,400M Freestyle,Silver
1896,Athens,Athletics,Athletics,USA,Men,100M,Bronze
1896,Athens,Athletics,Athletics,HUN,Men,100M,Bronze
1896,Athens,Athletics,Athletics,USA,Men,100M,Gold
1896,Athens,Athletics,Athletics,GER,Men,100M,Silver
1896,Athens,Athletics,Athletics,USA,Men,110M Hurdles,Gold
1896,Athens,Athletics,Athletics,GBR,Men,110M Hurdles,Silver
1896,Athens,Athletics,Athletics,FRA,Men,1500M,Bronze
1896,Athens,Athletics,Athletics,AUS,Men,1500M,Gold
1896,Athens,Athletics,Athletics,USA,Men,1500M,Silver
1896,Athens,Athletics,Athletics,GBR,Men,400M,Bronze
1896,Athens,Athletics,Athletics,USA,Men,400M,Gold
1896,Athens,Athletics,Athletics,USA,Men,400M,Silver
1896,Athens,Athletics,Athletics,GRE,Men,800M,Bronze
1896,Athens,Athletics,Athletics,AUS,Men,800M,Gold
1896,Athens,Athletics,Athletics,HUN,Men,800M,Silver
1896,Athens,Athletics,Athletics,GRE,Men,Discus Throw,Bronze
1896,Athens,Athletics,Athletics,USA,Men,Discus Throw,Gold
1896,Athens,Athletics,Athletics,GRE,Men,Discus Throw,Silver
1896,Athens,Athletics,Athletics,USA,Men,High Jump,Gold
...,...,...,...,...,...,...,...
2012,London,Wrestling,Wrestling Freestyle,AZE,Men,Wf 96 KG,Bronze
2012,London,Wrestling,Wrestling Freestyle,GEO,Men,Wf 96 KG,Bronze
2012,London,Wrestling,Wrestling Freestyle,CUB,Men,Wg 120 KG,Gold
2012,London,Wrestling,Wrestling Freestyle,EST,Men,Wg 120 KG,Silver
2012,London,Wrestling,Wrestling Freestyle,SWE,Men,Wg 120 KG,Bronze
2012,London,Wrestling,Wrestling Freestyle,TUR,Men,Wg 120 KG,Bronze
2012,London,Wrestling,Wrestling Freestyle,IRI,Men,Wg 55 KG,Gold
2012,London,Wrestling,Wrestling Freestyle,AZE,Men,Wg 55 KG,Silver
2012,London,Wrestling,Wrestling Freestyle,HUN,Men,Wg 55 KG,Bronze
2012,London,Wrestling,Wrestling Freestyle,RUS,Men,Wg 55 KG,Bronze
2012,London,Wrestling,Wrestling Freestyle,IRI,Men,Wg 60 KG,Gold
2012,London,Wrestling,Wrestling Freestyle,GEO,Men,Wg 60 KG,Silver
2012,London,Wrestling,Wrestling Freestyle,RUS,Men,Wg 60 KG,Bronze
2012,London,Wrestling,Wrestling Freestyle,JPN,Men,Wg 60 KG,Bronze
2012,London,Wrestling,Wrestling Freestyle,KOR,Men,Wg 66 KG,Gold
2012,London,Wrestling,Wrestling Freestyle,HUN,Men,Wg 66 KG,Silver
2012,London,Wrestling,Wrestling Freestyle,FRA,Men,Wg 66 KG,Bronze
2012,London,Wrestling,Wrestling Freestyle,GEO,Men,Wg 66 KG,Bronze
2012,London,Wrestling,Wrestling Freestyle,RUS,Men,Wg 74 KG,Gold
2012,London,Wrestling,Wrestling Freestyle,ARM,Men,Wg 74 KG,Silver
2012,London,Wrestling,Wrestling Freestyle,AZE,Men,Wg 74 KG,Bronze
2012,London,Wrestling,Wrestling Freestyle,LTU,Men,Wg 74 KG,Bronze
2012,London,Wrestling,Wrestling Freestyle,RUS,Men,Wg 84 KG,Gold
2012,London,Wrestling,Wrestling Freestyle,EGY,Men,Wg 84 KG,Silver
2012,London,Wrestling,Wrestling Freestyle,KAZ,Men,Wg 84 KG,Bronze
2012,London,Wrestling,Wrestling Freestyle,POL,Men,Wg 84 KG,Bronze
2012,London,Wrestling,Wrestling Freestyle,IRI,Men,Wg 96 KG,Gold
2012,London,Wrestling,Wrestling Freestyle,RUS,Men,Wg 96 KG,Silver
2012,London,Wrestling,Wrestling Freestyle,ARM,Men,Wg 96 KG,Bronze
2012,London,Wrestling,Wrestling Freestyle,SWE,Men,Wg 96 KG,Bronze

In [68]:
olym.index[2]='ssd' #index is immutable

TypeError: Index does not support mutable operations

In [69]:
n=olym.index.size
n

31165

In [70]:
s=[]#Creating new index
for i in range(0,n):
    s.append('Medal No {}'.format(i))

In [71]:
olym.reset_index(drop=True).head(2)

   Year    City     Sport Discipline Country Gender           Event   Medal
0  1896  Athens  Aquatics   Swimming     HUN    Men  100M Freestyle    Gold
1  1896  Athens  Aquatics   Swimming     AUT    Men  100M Freestyle  Silver

In [72]:
olym.set_index=s#Created index s is saved as new inde

In [73]:
olym.head(2)

,Year,City,Sport,Discipline,Country,Gender,Event,Medal
Athlete,,,,,,,,
"HAJOS, Alfred",1896,Athens,Aquatics,Swimming,HUN,Men,100M Freestyle,Gold
"HERSCHMANN, Otto",1896,Athens,Aquatics,Swimming,AUT,Men,100M Freestyle,Silver

In [74]:
olym.index.name='Medal no'#Giving our index a name
olym.head(1)

,Year,City,Sport,Discipline,Country,Gender,Event,Medal
Medal no,,,,,,,,
"HAJOS, Alfred",1896,Athens,Aquatics,Swimming,HUN,Men,100M Freestyle,Gold

Columns are also immutable

In [75]:
olym.columns.name='Info'#Setting new name for column

In [76]:
olym.head(1)

Info,Year,City,Sport,Discipline,Country,Gender,Event,Medal
Medal no,,,,,,,,
"HAJOS, Alfred",1896,Athens,Aquatics,Swimming,HUN,Men,100M Freestyle,Gold

In [88]:
olym.set_index=s
olym

Info,Year,City,Sport,Discipline,Country,Gender,Event,Medal
Medal no,,,,,,,,
"HAJOS, Alfred",1896,Athens,Aquatics,Swimming,HUN,Men,100M Freestyle,Gold
"HERSCHMANN, Otto",1896,Athens,Aquatics,Swimming,AUT,Men,100M Freestyle,Silver
"DRIVAS, Dimitrios",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Bronze
"MALOKINIS, Ioannis",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Gold
"CHASAPIS, Spiridon",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Silver
"CHOROPHAS, Efstathios",1896,Athens,Aquatics,Swimming,GRE,Men,1200M Freestyle,Bronze
"HAJOS, Alfred",1896,Athens,Aquatics,Swimming,HUN,Men,1200M Freestyle,Gold
"ANDREOU, Joannis",1896,Athens,Aquatics,Swimming,GRE,Men,1200M Freestyle,Silver
"CHOROPHAS, Efstathios",1896,Athens,Aquatics,Swimming,GRE,Men,400M Freestyle,Bronze
"NEUMANN, Paul",1896,Athens,Aquatics,Swimming,AUT,Men,400M Freestyle,Gold
"PEPANOS, Antonios",1896,Athens,Aquatics,Swimming,GRE,Men,400M Freestyle,Silver
"LANE, Francis",1896,Athens,Athletics,Athletics,USA,Men,100M,Bronze
"SZOKOLYI, Alajos",1896,Athens,Athletics,Athletics,HUN,Men,100M,Bronze
"BURKE, Thomas",1896,Athens,Athletics,Athletics,USA,Men,100M,Gold
"HOFMANN, Fritz",1896,Athens,Athletics,Athletics,GER,Men,100M,Silver
"CURTIS, Thomas",1896,Athens,Athletics,Athletics,USA,Men,110M Hurdles,Gold
"GOULDING, Grantley",1896,Athens,Athletics,Athletics,GBR,Men,110M Hurdles,Silver
"LERMUSIAUX, Albin",1896,Athens,Athletics,Athletics,FRA,Men,1500M,Bronze
"FLACK, Edwin",1896,Athens,Athletics,Athletics,AUS,Men,1500M,Gold
"BLAKE, Arthur",1896,Athens,Athletics,Athletics,USA,Men,1500M,Silver
"GMELIN, Charles",1896,Athens,Athletics,Athletics,GBR,Men,400M,Bronze
"BURKE, Thomas",1896,Athens,Athletics,Athletics,USA,Men,400M,Gold
"JAMISON, Herbert",1896,Athens,Athletics,Athletics,USA,Men,400M,Silver
"GOLEMIS, Dimitrios",1896,Athens,Athletics,Athletics,GRE,Men,800M,Bronze
"FLACK, Edwin",1896,Athens,Athletics,Athletics,AUS,Men,800M,Gold
"DANI, Nandor",1896,Athens,Athletics,Athletics,HUN,Men,800M,Silver
"VERSIS, Sotirios",1896,Athens,Athletics,Athletics,GRE,Men,Discus Throw,Bronze
"GARRETT, Robert",1896,Athens,Athletics,Athletics,USA,Men,Discus Throw,Gold
"PARASKEVOPOULOS, Panagiotis",1896,Athens,Athletics,Athletics,GRE,Men,Discus Throw,Silver
"CLARK, Ellery",1896,Athens,Athletics,Athletics,USA,Men,High Jump,Gold
...,...,...,...,...,...,...,...,...
"GAZYUMOV, Khetag",2012,London,Wrestling,Wrestling Freestyle,AZE,Men,Wf 96 KG,Bronze
"GOGSHELIDZE, George",2012,London,Wrestling,Wrestling Freestyle,GEO,Men,Wf 96 KG,Bronze
"LOPEZ NUNEZ, Mijain",2012,London,Wrestling,Wrestling Freestyle,CUB,Men,Wg 120 KG,Gold
"NABI, Heiki",2012,London,Wrestling,Wrestling Freestyle,EST,Men,Wg 120 KG,Silver
"EUREN, Johan",2012,London,Wrestling,Wrestling Freestyle,SWE,Men,Wg 120 KG,Bronze
"KAYAALP, Riza",2012,London,Wrestling,Wrestling Freestyle,TUR,Men,Wg 120 KG,Bronze
"SORYAN REIHANPOUR, Hamid Mohammad",2012,London,Wrestling,Wrestling Freestyle,IRI,Men,Wg 55 KG,Gold
"BAYRAMOV, Rovshan",2012,London,Wrestling,Wrestling Freestyle,AZE,Men,Wg 55 KG,Silver
"MODOS, Peter",2012,London,Wrestling,Wrestling Freestyle,HUN,Men,Wg 55 KG,Bronze
"SEMENOV, Mingiyan",2012,London,Wrestling,Wrestling Freestyle,RUS,Men,Wg 55 KG,Bronze
"NOROOZI, Omid Haji",2012,London,Wrestling,Wrestling Freestyle,IRI,Men,Wg 60 KG,Gold
"LASHKHI, Revaz",2012,London,Wrestling,Wrestling Freestyle,GEO,Men,Wg 60 KG,Silver
"KURAMAGOMEDOV, Zaur",2012,London,Wrestling,Wrestling Freestyle,RUS,Men,Wg 60 KG,Bronze
"MATSUMOTO, Ryutaro",2012,London,Wrestling,Wrestling Freestyle,JPN,Men,Wg 60 KG,Bronze
"KIM, Hyeonwoo",2012,London,Wrestling,Wrestling Freestyle,KOR,Men,Wg 66 KG,Gold
"LORINCZ, Tamas",2012,London,Wrestling,Wrestling Freestyle,HUN,Men,Wg 66 KG,Silver
"GUENOT, Steeve",2012,London,Wrestling,Wrestling Freestyle,FRA,Men,Wg 66 KG,Bronze
"TSKHADAIA, Manuchar",2012,London,Wrestling,Wrestling Freestyle,GEO,Men,Wg 66 KG,Bronze
"VLASOV, Roman",2012,London,Wrestling,Wrestling Freestyle,RUS,Men,Wg 74 KG,Gold
"JULFALAKYAN, Arsen",2012,London,Wrestling,Wrestling Freestyle,ARM,Men,Wg 74 KG,Silver
"AHMADOV, Emin",2012,London,Wrestling,Wrestling Freestyle,AZE,Men,Wg 74 KG,Bronze
"KAZAKEVIC, Aleksandr",2012,London,Wrestling,Wrestling Freestyle,LTU,Men,Wg 74 KG,Bronze
"KHUGAEV, Alan",2012,London,Wrestling,Wrestling Freestyle,RUS,Men,Wg 84 KG,Gold
"EBRAHIM, Karam Mohamed Gaber",2012,London,Wrestling,Wrestling Freestyle,EGY,Men,Wg 84 KG,Silver
"GAJIYEV, Danyal",2012,London,Wrestling,Wrestling Freestyle,KAZ,Men,Wg 84 KG,Bronze
"JANIKOWSKI, Damian",2012,London,Wrestling,Wrestling Freestyle,POL,Men,Wg 84 KG,Bronze
"REZAEI, Ghasem Gholamreza",2012,London,Wrestling,Wrestling Freestyle,IRI,Men,Wg 96 KG,Gold
"TOTROV, Rustam",2012,London,Wrestling,Wrestling Freestyle,RUS,Men,Wg 96 KG,Silver
"ALEKSANYAN, Artur",2012,London,Wrestling,Wrestling Freestyle,ARM,Men,Wg 96 KG,Bronze
"LIDBERG, Jimmy",2012,London,Wrestling,Wrestling Freestyle,SWE,Men,Wg 96 KG,Bronze

In [77]:
tt=pd.read_csv('titanic.csv')
tt.reset_index(inplace=True,drop=True)